project_id = "iykcvtemszqklsmwmzid"

[functions.admin-upload]
verify_jwt = false

[functions.process-file-v2]
verify_jwt = false

[functions.trigger-file-processing]
verify_jwt = false

[functions.delete-kb-file]
verify_jwt = false

[functions.trigger-chat-response]
verify_jwt = false

[functions.handle-chat-response]
verify_jwt = false