// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iykcvtemszqklsmwmzid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5a2N2dGVtc3pxa2xzbXdtemlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTE1NjIsImV4cCI6MjA3MDIyNzU2Mn0.3so9xUxQXhtv_wK38nWiarqMuQ2vVm350u5-1rYgQbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});